channels:
  - bioconda
  - conda-forge
dependencies:
  - python >= 3.7
  - datrie
  - wrapt
  - pyyaml
  - requests
  - appdirs
  - jsonschema
  - snakemake-minimal >=7.3
  - jinja2
  - networkx =2.5
  - matplotlib
  - pandas
  - graphviz
  - bcftools =1.15
  - samtools =1.15
  - bwa =0.7.17
  - pysam =0.19
  - pygments
  - gcc
  - gxx
  - make
  - ensembl-vep=109
  - perl
  - perl-app-cpanminus
  - Flask==2.1.2